name: Pull Request Validation

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      pipeline: ${{ steps.filter.outputs.pipeline }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Check which files changed
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          pipeline:
            - '.github/workflows/**'

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs:
    - changes
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitLint
      run: sudo apt-get install -y gitlint
    - name: Validate Commit Messages
      run: gitlint --commits "origin/main..HEAD"

    - name: Install GitHub action-validator
      uses: asdf-vm/actions/install@v3
      if: ${{ needs.changes.outputs.pipeline == 'true' }}
      with:
        tool_versions: |
          action-validator 0.5.4
    - name: Validate GitHub Actions
      if: ${{ needs.changes.outputs.pipeline == 'true' }}
      run: |
        find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) \
          | xargs -I {} action-validator --verbose {}
